TARGET		=Sphere 

$(TARGET):	OctaSphere2Linux.o  gl2ps.o 
	g++ -g -o $(TARGET) OctaSphere2Linux.o  gl2ps.o  \
	 `sdl-config --libs` -lGL -lGLU -lm

OctaSphere2Linux.o:   
	g++ -g  -c OctaSphere2.cpp `sdl-config --cflags`

gl2ps.o:
	cc -g -c gl2ps.c 

clean:
	rm -f $(TARGET) *.o  core
