TARGET		=Sphere 

$(TARGET):	IcoSphereLinux.o  gl2ps.o 
	g++ -g -o $(TARGET) IcoSphereLinux.o  gl2ps.o  \
	 `sdl-config --libs` -lGL -lGLU -lm

IcoSphereLinux.o:   
	g++ -g  -c IcoSphereLinux.cpp `sdl-config --cflags`

gl2ps.o:
	cc -g -c gl2ps.c 

clean:
	rm -f $(TARGET) *.o  core
