TARGET		=Sphere 

$(TARGET):	OctaSphereLinux.o  gl2ps.o 
	g++ -g -o $(TARGET) OctaSphereLinux.o  gl2ps.o  \
	 `sdl-config --libs` -lGL -lGLU -lm

OctaSphereLinux.o:   
	g++ -g  -c OctaSphereLinux.cpp `sdl-config --cflags`

gl2ps.o:
	cc -g -c gl2ps.c 

clean:
	rm -f $(TARGET) *.o  core
