TARGET		=Sphere 

$(TARGET):	IcoSphere2Linux.o  gl2ps.o 
	g++ -g -o $(TARGET) IcoSphere2Linux.o  gl2ps.o  \
	 `sdl-config --libs` -lGL -lGLU -lm

IcoSphere2Linux.o:   
	g++ -g  -c IcoSphere2Linx.cpp `sdl-config --cflags`

gl2ps.o:
	cc -g -c gl2ps.c 

clean:
	rm -f $(TARGET) *.o  core
